# Generated by Django 2.1.15 on 2021-08-25 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('principal', models.CharField(max_length=255)),
                ('income', models.IntegerField()),
                ('drivers', models.ManyToManyField(to='core.Driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
