# Generated by Django 2.1.15 on 2021-08-27 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teamnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamnew',
            name='drivers',
        ),
        migrations.RemoveField(
            model_name='teamnew',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='drivers',
        ),
        migrations.AddField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Team'),
        ),
        migrations.DeleteModel(
            name='TeamNew',
        ),
    ]
